services:
  # Aplicação Laravel
  app:
    build: .
    container_name: ri-ifba-app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=ri_ifba_v1
      - DB_USERNAME=postgres
      - DB_PASSWORD=201099
    restart: unless-stopped
    command: sh -lc "if [ ! -f vendor/autoload.php ]; then composer install --no-interaction --prefer-dist; fi && php artisan serve --host=0.0.0.0 --port=8000"


  # Banco de dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: ri-ifba-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ri_ifba_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 201099
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  vendor_data:
  node_modules_data:
